#
# Copyright (C) 2025 The Android Open Source Project
# Copyright (C) 2025 OrangeFox Recovery Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/vivo/PD1936

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a9

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := msmnile
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := msmnile

# Display
TARGET_SCREEN_DENSITY := 480

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := console=null earlycon=null androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 product.version=PD1936_A_9.15.14 fingerprint.abbr=11/RP1A.200720.012 region_ver=W10 buildvariant=user androidboot.securebootkeyhash=2c0a52ffbd8db687b56f6a98d8840f46597a4dde6d9dc8d00039873ce6d74f60 androidboot.securebootkeyver=4
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_CONFIG := PD1936_defconfig
TARGET_KERNEL_SOURCE := kernel/vivo/PD1936

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
else
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
endif

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4294967296 # 4GB (estimate)
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824 # 1GB (estimate)
BOARD_VENDORIMAGE_PARTITION_SIZE := 1610612736 # 1.5GB (estimate)
BOARD_METADATAIMAGE_PARTITION_SIZE := 16777216 # 16MB
BOARD_DTBOIMG_PARTITION_SIZE := 8388608 # 8MB

BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_METADATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# OrangeFox Configuration
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := true
FOX_USE_NANO_EDITOR := true
FOX_USE_BASH_SHELL := true
FOX_USE_TAR_BINARY := true
FOX_USE_ZIP_BINARY := true
FOX_USE_XZ_UTILS := true
FOX_USE_SED_BINARY := true
FOX_USE_GREP_BINARY := true
FOX_USE_LZMA_COMPRESSION := true

# Display
FOX_THEME := "11"
FOX_CUSTOM_BATTERY_PERCENTAGE := true
FOX_CUSTOM_BATTERY_CAPACITY := "4000"
FOX_CUSTOM_BATTERY_TEMP_PATH := "/sys/class/power_supply/battery/temp"
FOX_CUSTOM_BATTERY_VOLTAGE_PATH := "/sys/class/power_supply/battery/voltage_now"
FOX_CUSTOM_BATTERY_CURRENT_PATH := "/sys/class/power_supply/battery/current_now"

# Brightness
FOX_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
FOX_MAX_BRIGHTNESS := 255
FOX_DEFAULT_BRIGHTNESS := 160

# Version
FOX_VERSION := R11.1_1
FOX_BUILD_TYPE := Stable
FOX_MAINTAINER := YourName
FOX_MAINTAINER_PATCH_VERSION := 1
# Features
FOX_SUPPORT_INPUT_VERIFY := true
FOX_SUPPORT_INPUT_DISABLE_VERIFICATION := false
FOX_SUPPORT_PREBUILT_KERNEL := true
FOX_SUPPORT_PREBUILT_DTB := true
FOX_SUPPORT_PREBUILT_DTBO := true
# Display
TARGET_SCREEN_DENSITY := 480
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
TW_THEME := portrait_hdpi

# Status bar
TW_STATUS_ICONS_ALIGN := center
TW_Y_OFFSET := 80
TW_H_OFFSET := 0

# Recovery模式所需的设备模块 - 触摸屏固件
TARGET_RECOVERY_DEVICE_MODULES += \
    touch_firmwares_recovery.bin \
    TP-CONFIG-FW-PD1936-LCMID33-VER0x0028.bin \
    TP-CONFIG-FW-PD1936-LCMID33-VER0x002C.bin \
    TP-FW-PD1936-LCMID33-VER0x502100028.bin \
    TP-FW-PD1936-LCMID33-VER0x50213002C.bin

# 触摸屏固件配置
TW_LOAD_VENDOR_MODULES := true
TW_LOAD_VENDOR_BINS := true
TW_OEM_BUILD := true
TW_INCLUDE_CRYPTO_FBE := true

# 指定固件安装路径
TW_RECOVERY_ADDITIONAL_RELINK_BINARY_FILES += \
    $(TARGET_OUT_VENDOR)/bin/tp_firmware_selector.sh \
    $(TARGET_OUT_VENDOR)/lib/modules/touchscreen.ko

TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/libtouchscreen.so

# Crypto
FOX_USE_DATA_DECRYPTION := true
FOX_USE_F2FS_COMPRESSION := true
FOX_USE_FSCRYPT := true
FOX_USE_DM_VERITY := true
FOX_USE_AVB := true

# 添加触摸屏固件支持
FOX_SUPPORT_TOUCH_FIRMWARE := true
FOX_TOUCH_FIRMWARE_PATH := "/vendor/firmware/"
FOX_TOUCH_DRIVER_MODULE := "touchscreen_driver.ko"
# Crypto
FOX_USE_DATA_DECRYPTION := true
FOX_USE_F2FS_COMPRESSION := true
FOX_USE_FSCRYPT := true
FOX_USE_DM_VERITY := true
FOX_USE_AVB := true

# Exclusions
FOX_EXCLUDE_NANO_EDITOR := false
FOX_EXCLUDE_BASH_SHELL := false
FOX_EXCLUDE_TAR_BINARY := false
FOX_EXCLUDE_ZIP_BINARY := false
FOX_EXCLUDE_XZ_UTILS := false
FOX_EXCLUDE_SED_BINARY := false
FOX_EXCLUDE_GREP_BINARY := false

# Logging
FOX_INCLUDE_LOG := true
FOX_LOG_PATH := "/tmp/recovery.log"

# Device-specific
FOX_DEVICE_MODEL := "V1936A"
FOX_DEVICE_BRAND := "vivo"
FOX_DEVICE_NAME := "PD1936"

# Misc
FOX_USE_SYSTEM_PROPS := true
FOX_USE_SPECIFIC_PROPS := \
    "ro.build.fingerprint=ro.system.build.fingerprint;ro.build.version.incremental"
